### ISSUE TITLE
The output listing of multiple bonds are not separated by a space

### ISSUE THREAD

**Issue by worsco** [ankkzz/getBondStatus#1]
The output of multiple bonds from "getBondStatus -l" is
Bonds: bond1bond0

Change line 69 to:

     print STDOUT "Bonds: ", join(' ',@bonds) ,"\n" if $verbose eq 1;

Now, if there are multiple bonds, the output is:
Bonds: bond1 bond0

**Comment by ankkzz** [comment]
Cool ... I shall incorporate suggested change.

Thanks!

**Comment by ankkzz** [comment]
Committed the changes against the latest commit.
